### ISSUE TITLE
jboss logmanager

### ISSUE THREAD

**Issue by matzew** [wildfly-swarm/example-jpa-jaxrs-cdi#1]
@kenfinnigan looks like some dependency is missing?

```
Could not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.util.logging.LogManager$1.run(LogManager.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.<clinit>(LogManager.java:181)
	at java.util.logging.Logger.demandLogger(Logger.java:339)
	at java.util.logging.Logger.getLogger(Logger.java:393)
	at org.jboss.shrinkwrap.api.ConfigurationBuilder.<clinit>(ConfigurationBuilder.java:51)
	at org.wildfly.swarm.container.Container.createShrinkWrapDomain(Container.java:46)
	at org.wildfly.swarm.container.Container.<init>(Container.java:38)
	at org.wildfly.swarm.examples.jpa.Main.main(Main.java:15)
May 29, 2015 10:16:39 AM org.jboss.msc.service.ServiceContainerImpl <clinit>
INFO: JBoss MSC version 1.2.4.Final
May 29, 2015 10:16:39 AM org.jboss.as.server.ApplicationServerService start
INFO: WFLYSRV0049: WildFly Core 1.0.0.CR1 "Kenny" starting
May 29, 2015 10:16:40 AM org.jboss.as.controller.AbstractOperationContext executeStep
ERROR: WFLYCTL0013: Operation ("parallel-extension-add") failed - address: ([])
java.lang.RuntimeException: WFLYCTL0079: Failed initializing module org.jboss.as.logging
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:115)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:803)
	at org.jboss.as.controller.AbstractOperationContext.doCompleteStep(AbstractOperationContext.java:601)
	at org.jboss.as.controller.AbstractOperationContext.completeStepInternal(AbstractOperationContext.java:354)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:330)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1183)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:429)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:327)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:313)
	at org.jboss.as.server.ServerService.boot(ServerService.java:381)
	at org.jboss.as.server.ServerService.boot(ServerService.java:356)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:271)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$1.execute(ParallelExtensionAddHandler.java:107)
	... 12 more
Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
	at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:144)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:131)
	at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
	at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

May 29, 2015 10:16:40 AM org.jboss.as.server.ServerService boot
FATAL: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
May 29, 2015 10:16:40 AM org.jboss.as.server.BootstrapImpl$ShutdownHook run
INFO: WFLYSRV0220: Server shutdown has been requested.
```

**Comment by kenfinnigan** [comment]
I can't replicate the problem.

Did you build the latest HEAD of WildFly Swarm?

**Comment by matzew** [comment]
yeah :)

On Fri, May 29, 2015 at 3:34 PM, Ken Finnigan <notifications@github.com>
wrote:

> I can't replicate the problem.
>
> Did you build the latest HEAD of WildFly Swarm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wildfly-swarm/example-jpa-jaxrs-cdi/issues/1#issuecomment-106803754>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by jamezp** [comment]
How are you running it? From the command line, IDE, etc. The log manager should be set before anything is launched.

**Comment by kenfinnigan** [comment]
@matzew I've modified wildfly-swarm to explicitly add logging as a dependency for JPA, but it was already being included through another dependency.

So I don't think that's going to change your problem, which I'm still confused about.

@jamezp, are you able to run this example with latest HEAD?

**Comment by jamezp** [comment]
@kenfinnigan TBH I didn't test it, but I can :) I just know the message all too well.

**Comment by kenfinnigan** [comment]
@jamezp no problem, you know logging better than anyone ;-)

**Comment by jamezp** [comment]
No issues for me either using the command line or `mvn wildfly-swarm/:run` from the command line.

**Comment by kenfinnigan** [comment]
@jamezp are you on a Linux distro?

**Comment by jamezp** [comment]
Yeah Fedora. I've got a Mac I can run it on and a Windows VM if needed too. I'd *think* something like this wouldn't be OS related. Though you never know :)

**Comment by kenfinnigan** [comment]
Ok.

I think, from memory, @matzew would be Mac.

Agree that it would be a weird error to be OS specific

**Comment by matzew** [comment]
ISsues on IDE and 
```
mvn wildfly-swarm:run
```

**Comment by matzew** [comment]
and yes, I am a Mac weenie

**Comment by jamezp** [comment]
Seems to be working for me with `mvn wildfly-swarm:run` on OS X. I've built the upstream of WildFly Swarm.

**Comment by matzew** [comment]
now, with java8 it works :-)
